#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0;
minute=0;
while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	while [ $minute -le 59 ]; do
		echo $minute
		((minute++))
	done

	((hour++))
	minute=1
done
